// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRlip7F5AwTjky7Rws3b9SMOilVE0atbs',
    appId: '1:1096006179653:web:99bc9c6e75e1f62ad13c2c',
    messagingSenderId: '1096006179653',
    projectId: 'flutter-56b48',
    authDomain: 'flutter-56b48.firebaseapp.com',
    storageBucket: 'flutter-56b48.firebasestorage.app',
    measurementId: 'G-QH310XX3DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqiRd-0yzHWG8GNlXshf6FSd3xsThyWGM',
    appId: '1:1096006179653:android:64e6b1066e821b3ed13c2c',
    messagingSenderId: '1096006179653',
    projectId: 'flutter-56b48',
    storageBucket: 'flutter-56b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuV3CS3CFrWSsL1aPKI2C_3xQDSlz4x58',
    appId: '1:1096006179653:ios:5fcf12fb868c13b5d13c2c',
    messagingSenderId: '1096006179653',
    projectId: 'flutter-56b48',
    storageBucket: 'flutter-56b48.firebasestorage.app',
    androidClientId: '1096006179653-3nlpf4psvorali0o05bre16sqkdelc52.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuV3CS3CFrWSsL1aPKI2C_3xQDSlz4x58',
    appId: '1:1096006179653:ios:5fcf12fb868c13b5d13c2c',
    messagingSenderId: '1096006179653',
    projectId: 'flutter-56b48',
    storageBucket: 'flutter-56b48.firebasestorage.app',
    androidClientId: '1096006179653-3nlpf4psvorali0o05bre16sqkdelc52.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRlip7F5AwTjky7Rws3b9SMOilVE0atbs',
    appId: '1:1096006179653:web:c0b53f5c19458520d13c2c',
    messagingSenderId: '1096006179653',
    projectId: 'flutter-56b48',
    authDomain: 'flutter-56b48.firebaseapp.com',
    storageBucket: 'flutter-56b48.firebasestorage.app',
    measurementId: 'G-96B8PQY37D',
  );
}
